### ISSUE TITLE
Make password encoding configurable.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-project/fluid-express-user#14]
Currently we use `sha1` encoding, which is not optimal.  We also don't provide any means to configure this.  This issue will cover:

1. Updating to use a new default encoding.
2. Making it possible and testing configuring this in real time.
3. Testing working with records that use the legacy `sha1` encoding when that is no longer the default.

**Comment by the-t-in-rtf** [comment]
I have been preparing for this by looking at the current password strategy used by CouchDB, which seems to still use the default `sha1` digest.  As I mentioned to @jobara in chats, the requirement to use real CouchDB user accounts was only temporarily advantageous years ago.  Rather than attempt to maintain this support, I propose releasing a major version that removes support for CouchDB style usernames, and removes the prefix field.  We would leave migration hints in the release notes, but would not provide a migration script.

For starters, we need to select the desired default algorithm.  Here is the list returned by `(require ("crypto")).getHashes()`:


```
  'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA3-224',
  'RSA-SHA3-256',
  'RSA-SHA3-384',
  'RSA-SHA3-512',
  'RSA-SHA384',
  'RSA-SHA512',
  'RSA-SHA512/224',
  'RSA-SHA512/256',
  'RSA-SM3',
  'blake2b512',
  'blake2s256',
  'id-rsassa-pkcs1-v1_5-with-sha3-224',
  'id-rsassa-pkcs1-v1_5-with-sha3-256',
  'id-rsassa-pkcs1-v1_5-with-sha3-384',
  'id-rsassa-pkcs1-v1_5-with-sha3-512',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5-sha1',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha3-224',
  'sha3-256',
  'sha3-384',
  'sha3-512',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512-224',
  'sha512-224WithRSAEncryption',
  'sha512-256',
  'sha512-256WithRSAEncryption',
  'sha512WithRSAEncryption',
  'shake128',
  'shake256',
  'sm3',
  'sm3WithRSAEncryption',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool'
```

@greatislander, as you raised the concerns about sha1, I was hoping you'd have an informed opinion about which you'd like to use.

**Comment by the-t-in-rtf** [comment]
> Testing working with records that use the legacy `sha1` encoding when that is no longer the default.

Just to flesh this out a little, I realised that I wanted to confirm that:

1. Logins with the previous default digest will continue to work.
2. Password resets correctly use the server's configured digest (which gives us a migration strategy for legacy users).

**Comment by jobara** [comment]
@the-t-in-rtf it sounds like this will make a change to the document id in the database. It would be good for this also be configurable. 

Also @BlueSlug might have some thoughts on the default algorithm used.

**Comment by greatislander** [comment]
@the-t-in-rtf @jobara I don't think I was the one who raised concerns about `sha-1`. I haven't actually done any work on this project. Was it @klown?

**Comment by jobara** [comment]
@greatislander and @the-t-in-rtf it was probably @BlueSlug.

**Comment by klown** [comment]
@greatislander, @jobara , @the-t-in-rtf it wasn't me.

**Comment by BlueSlug** [comment]
As @jobara said, I believe it was me :) I'm going to do a little more reading, since my initial suggestion was based on work I did during my DevOps days to replace all of my organization's SHA-1 SSL certs with SHA-256, and my information may now be out of date.

The fact that SHA-1 is now bunk is not in question, but mainly whether SHA-256 is still an appropriate replacement. I'll do a little reading and see if that's still the case, or if any more suitable algorithms have taken its place (e.g. SHA-3, etc.)

**Comment by the-t-in-rtf** [comment]
Sorry @greatislander, I was half-remembering a chat, glad the right person eventually got pulled in.

>  It sounds like this will make a change to the document id in the database. It would be good for this also be configurable.

Yes, I support systems that use the old IDs as well, so we'd need basic instructions on migrating.  As far as I know the migration could be as simple as making a GET call to the bulk_data endpoint, finding and removing the prefixes, and then submitting the results to the bulk_data endpoint.
